name: stock_helper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi[all]
    - uvicorn[standard]
    - sqlalchemy[asyncio]
    - asyncpg
    - alembic
    - pydantic-settings
    - loguru
    - pytest
    - pytest-asyncio
    - black
    - isort
    - flake8
    - mypy
    - httpx
    - structlog
    - dependency-injector
    - python-json-logger
    - prometheus-client
